[pytest]
addopts = -v --cov=composition.messaging --cov=abstraction.discount_calculator --cov=bisection_method.square_bisection --cov=abstraction.player_interface --cov=class_properties.game_character_stats_tracker --cov=binary_search.binary_search --cov=merge_sort.sample_sort --cov=linked_list.linked_list --cov=hash_table.hash_table --cov-report=term-missing --cov-report=html
norecursedirs = .* venv .venv env
