[pytest]
addopts = -v --cov=composition.messaging --cov=abstraction.discount_calculator --cov=class_properties.game_character_stats_tracker --cov-report=term-missing
norecursedirs = .* venv .venv env
