[pytest]
addopts = -v --cov=composition.messaging --cov=abstraction.discount_calculator --cov=abstraction.player_interface --cov=class_properties.game_character_stats_tracker --cov-report=term-missing --cov-report=html
norecursedirs = .* venv .venv env
